export const documentTypes = [
  { value: "CC", label: "Cédula de ciudadanía" },
  { value: "CE", label: "Cédula de extranjería" },
  { value: "TI", label: "Tarjeta de identidad" },
  { value: "PPT", label: "Permiso por Protección Temporal (PPT)" },
  { value: "PASS", label: "Pasaporte" },
  { value: "PEP", label: "Permiso Especial de Permanencia (PEP)" },
] as const;
export type DocumentType = (typeof documentTypes)[number]["value"];
export function validDocument(type: string, number: string): boolean {
  if (!documentTypes.some((d) => d.value === type)) return false;
  return (
    type === "PASS" || type === "CE" ? /^[A-Z0-9]{3,20}$/ : /^\d{5,15}$/
  ).test(number);
}
export const cities = [
  "Bogotá D.C.",
  "Medellín",
  "Cali",
  "Barranquilla",
  "Cartagena",
  "Cúcuta",
  "Bucaramanga",
  "Pereira",
  "Santa Marta",
  "Ibagué",
  "Pasto",
  "Manizales",
  "Neiva",
  "Villavicencio",
  "Armenia",
  "Valledupar",
  "Montería",
  "Sincelejo",
  "Popayán",
  "Tunja",
  "Riohacha",
  "Quibdó",
  "Florencia",
  "Yopal",
  "Arauca",
  "Mocoa",
  "San Andrés",
  "Leticia",
  "San José del Guaviare",
  "Mitú",
  "Inírida",
  "Puerto Carreño",
  "Soacha",
  "Bello",
  "Envigado",
  "Itagüí",
  "Rionegro",
  "Palmira",
  "Buenaventura",
  "Tuluá",
  "Dosquebradas",
  "Floridablanca",
  "Girón",
  "Piedecuesta",
  "Soledad",
  "Malambo",
  "Chía",
  "Cajicá",
  "Zipaquirá",
  "Facatativá",
  "Funza",
  "Mosquera",
  "Fusagasugá",
  "Girardot",
  "Duitama",
  "Sogamoso",
  "Barrancabermeja",
  "Ocaña",
  "Apartadó",
  "Turbo",
  "Tumaco",
];
